### ISSUE TITLE
Download MESSIDOR and segmentations

### ISSUE THREAD

**Issue by wuhanhui** [ignaciorlando/fundus-fractal-analysis#2]
Nice project. The link of  vessel segmentation is missing. Can you check it ? Thanks

**Comment by ignaciorlando** [comment]
Hi @wuhanhui! The link is working perfectly (even in my cell phone, in which I'm not logged in on Box). If you are using wget or right clic and save as it won't work. You just have to clic on the link, which will bring you to the Box folder, and there you will find all the vessel segmentation. Take into account that all of them are downsampled to approximately the same resolution on DRIVE. 

By the way, as we didn't submit our paper yet, of you use this data on your research please cite our TBME and MICCAI papers on vessel segmentation. You will find the corresponding citations on one of my repos here. Once we get our PMB paper accepted we will let you know. 

Good luck, and let me know if you can't make the link work yet!

**Comment by wuhanhui** [comment]
Thanks for you help. I have try to download that with a proxy and it works now. Maybe this website is blocked in my country.
